name: CI/CD Auth Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ESTÁGIO 1: Build & Test
  build-and-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      - name: Instalar Dependências
        run: go mod download

      - name: Compilar Aplicação
        run: go build -o auth-service .

      - name: Testes Unitários
        run: |
          echo "Nenhum teste unitário detectado no repositório."
          echo "Build validado. Avançando para Linter e Segurança..."

  # ESTÁGIO 2: DevSecOps (Linter, SAST e SCA)
  security-and-lint:
    name: Linter & Security Scan
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.13'

      - name: Linter (golangci-lint)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: SAST (Gosec)
        uses: securego/gosec@master
        with:
          args: '-severity high ./...'

      - name: SCA (Trivy Filesystem)
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

  # ESTÁGIO 3: Docker, Scan e Push
  docker-build-and-scan:
    name: Docker Build, Scan & Push
    needs: security-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da Imagem Docker local
        run: docker build -t auth-service:${{ github.sha }} .

      - name: Container Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'auth-service:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

      # --- INTEGRAÇÃO COM DOCKER HUB ---
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da Imagem Validada
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 1. Renomeia a imagem local para o formato exigido pelo Docker Hub
          docker tag auth-service:$IMAGE_TAG $DOCKER_USER/auth-service:$IMAGE_TAG
          docker tag auth-service:$IMAGE_TAG $DOCKER_USER/auth-service:latest
          
          # 2. Envia as imagens para o repositório público
          docker push $DOCKER_USER/auth-service:$IMAGE_TAG
          docker push $DOCKER_USER/auth-service:latest