name: CI/CD Auth Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ESTÁGIO 1: Build & Test
  build-and-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Instalar Dependências
        run: go mod download

      - name: Compilar Aplicação
        run: go build -o auth-service .

      - name: Testes Unitários
        run: |
          echo "Nenhum teste unitário detectado no repositório."
          echo "Build validado. Avançando para Linter e Segurança..."

  # ESTÁGIO 2: DevSecOps (Linter, SAST e SCA)
  security-and-lint:
    name: Linter & Security Scan
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Linter (golangci-lint)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: SAST (Gosec)
        uses: securego/gosec@master
        with:
          args: '-severity high ./...'

      - name: SCA (Trivy Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

  # ESTÁGIO 3: Docker e Container Scan
  docker-build-and-scan:
    name: Docker Build & Image Scan
    needs: security-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da Imagem Docker
        run: docker build -t auth-service:${{ github.sha }} .

      - name: Container Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'auth-service:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
